name: Windows Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install WiX Toolset
        run: choco install wixtoolset

      - name: Run WiX Installer
        run: |
          & "C:\ProgramData\chocolatey\lib\wixtoolset\tools\wix311.exe" /install /quiet /norestart

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build x64
        run: $env:GOOS="windows"; $env:GOARCH="amd64"; go build -ldflags -H=windowsgui -o dist/go-gist-it-x64.exe

      - name: Build x86
        run: $env:GOOS="windows"; $env:GOARCH="386"; go build -ldflags -H=windowsgui -o dist/go-gist-it-x86.exe

      - name: Build Installer x64
        run: |
          & "C:\Program Files (x86)\WiX Toolset v3.11\bin\candle.exe" go-gist-it-wix-x64.wxs
          & "C:\Program Files (x86)\WiX Toolset v3.11\bin\light.exe" go-gist-it-wix-x64.wixobj -o go-gist-it-installer-x64.msi
        shell: pwsh

      - name: Build Installer x86
        run: |
          & "C:\Program Files (x86)\WiX Toolset v3.11\bin\candle.exe" go-gist-it-wix-x86.wxs
            & "C:\Program Files (x86)\WiX Toolset v3.11\bin\light.exe" go-gist-it-wix-x86.wixobj -o go-gist-it-installer-x86.msi

      - name: Upload installer artifact x64
        uses: actions/upload-artifact@v2
        with:
          name: installer-x64
          path: ./go-gist-it-installer-x64.msi

      - name: Upload installer artifact x86
        uses: actions/upload-artifact@v2
        with:
          name: installer-x86
          path: ./go-gist-it-installer-x86.msi

  release:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download installer artifact x64
        uses: actions/download-artifact@v2
        with:
          name: installer-x64

      - name: Download installer artifact x86
        uses: actions/download-artifact@v2
        with:
          name: installer-x86

      - name: Set Tag
        run: |
          git tag release-${{ github.sha }}
          git push origin release-${{ github.sha }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: release-${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release x64
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{ github.sha }}
          files: ./go-gist-it-installer-x64.msi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release x86
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{ github.sha }}
          files: ./go-gist-it-installer-x86.msi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

