name: Windows Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install WiX Toolset
        run: choco install wixtoolset

      - name: Run WiX Installer
        run: |
          & "C:\ProgramData\chocolatey\lib\wixtoolset\tools\wix311.exe" /install /quiet /norestart

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build Go app
        run: go build -ldflags -H=windowsgui -o dist/go-gist-it.exe

      - name: Build Installer
        run: |
          & "C:\Program Files (x86)\WiX Toolset v3.11\bin\candle.exe" go-gist-it-wix.wxs
          & "C:\Program Files (x86)\WiX Toolset v3.11\bin\light.exe" go-gist-it-wix.wixobj -o go-gist-it-installer.exe
        shell: pwsh

      - name: Upload installer artifact
        uses: actions/upload-artifact@v2
        with:
          name: installer
          path: ./go-gist-it-installer.exe

  release:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download installer artifact
        uses: actions/download-artifact@v2
        with:
          name: installer

      - name: Set Tag
        run: |
          git tag release-${{ github.sha }}
          git push origin release-${{ github.sha }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: release-${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./go-gist-it-installer.exe
          asset_name: go-gist-it-installer.exe
          asset_content_type: application/exe
