name: Windows Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install WiX Toolset
        run: choco install wixtoolset

      - name: Install WiX Toolset
        run: |
          & "C:\ProgramData\chocolatey\lib\wixtoolset\tools\wix311.exe" /install /quiet /norestart

      - name: List WiX directories
        run: |
          Get-ChildItem -Path "C:\ProgramData\chocolatey\lib\wixtoolset\tools" -Recurse

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build Go app
        run: go build -ldflags -H=windowsgui -o dist/go-gist-it.exe

      - name: Build Installer
        run: |
          & "C:\Program Files (x86)\WiX Toolset v3.11\bin\candle.exe" go-gist-it-wix.wxs
          & "C:\Program Files (x86)\WiX Toolset v3.11\bin\light.exe" go-gist-it-wix.wixobj -o go-gist-it-installer.exe
        shell: pwsh

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output-installer-name.exe
          asset_name: go-gist-it-installer.exe
          asset_content_type: application/exe
